### ISSUE TITLE
Unsupported version of export! This tool supports [2.81.0, 2.82.0], but export is 2.101.0

### ISSUE THREAD

**Issue by timashev** [wireapp/backup-export-tool#12]
I'm trying to use this tool on a backup create with the most recent version of Wire app for iOS, and getting this error message:

```
java.lang.IllegalArgumentException: Unsupported version of export! This tool supports [2.81.0, 2.82.0], but export is 2.101.0
	at com.wire.backups.exports.ios.database.ConsistencyVerificationKt.verifyDatabaseMetadata(ConsistencyVerification.kt:6)
	at com.wire.backups.exports.ios.ApiKt.processIosBackup(Api.kt:62)
	at com.wire.backups.exports.api.IosBackupExport.exportDatabase(IosBackupExport.kt:26)
	at com.wire.backups.exports.exporters.IosExporter.run(IosExporter.java:55)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:28)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.wire.backups.exports.Service.main(Service.java:15)
```

**Comment by LukasForst** [comment]
This tool was designed to be used by the corporate users and we no longer provide support for this.

However, in [ConsistencyVerification.kt](https://github.com/wireapp/backup-export-tool/blob/master/src/main/kotlin/com/wire/backups/exports/ios/database/ConsistencyVerification.kt#L11) there's a list of supported backup versions. I'm not aware of any change that would be breaking between the supported ones and current one `2.101.0` - so you can just insert this number to the code and see if that works or not.

**Comment by timashev** [comment]
Thanks @LukasForst, I already did that and even created some PDFs, but the problem is that none of the user avatars or images/photos are saved to PDF by this tool. I see a list of errors like this:
```
Aug 30, 2022 3:14:26 PM com.wire.xenon.tools.Logger error
SEVERE: Cache.getProfileImage: key: 3-2-8f435643-c855-4526-a9aa-dedabc604375, ex: HttpException: code: 400, msg: Failed reading: Invalid domain name: cannot be dotless domain. AssetId: 3-2-8f435643-c855-4526-a9aa-dedabc604375, label: null
Aug 30, 2022 3:14:32 PM com.wire.xenon.tools.Logger error
SEVERE: Cache.getAssetFile: HttpException: code: 400, msg: Failed reading: Invalid domain name: cannot be dotless domain. AssetId: 3-2-4fcb5631-8173-4a6b-8653-5fa2f40148da, label: null
```

As you can see `Cache.getProfileImage` and `Cache.getAssetFile` are failing. Could you please point me out where to look for code changes and ideally give me some direction on upgrading the export tool code and fixing this image loading problem?
