### ISSUE TITLE
Error when trying to export an Android backup

### ISSUE THREAD

**Issue by frabrunelle** [wireapp/backup-export-tool#8]
Hi, I get this error when trying to use this tool with an Android backup:

```
java.lang.NullPointerException
	at com.wire.backups.exports.exporters.AndroidExporter.lambda$getCollector$16(AndroidExporter.java:266)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at com.wire.backups.exports.exporters.AndroidExporter.getCollector(AndroidExporter.java:263)
	at com.wire.backups.exports.exporters.AndroidExporter.lambda$appendMembers$7(AndroidExporter.java:160)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.wire.backups.exports.exporters.AndroidExporter.appendMembers(AndroidExporter.java:159)
	at com.wire.backups.exports.exporters.AndroidExporter.run(AndroidExporter.java:68)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:27)
	at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.wire.backups.exports.Service.main(Service.java:15)
```

Thanks for your help!

**Comment by SchoolGuy** [comment]
Edit: My export was done on the Android App 3.80.23

I too get the same stacktrace. To add some additional information:

```
Backup to PDF converter version: null

Directories had to be created: true
No content.No content.No content.No content.No content.No content.No content.No content.No content.No content.No content.No content.[main] WARN com.wire.backups.exports.android - Database is missing referenced asset: Message(id=<redacted>, conversationId=<redacted>, messageType=VideoAsset, userId=<redacted>, content=null, protos=[<a list of numbers>], time=1603140623664, members=null, name=null, editTime=0, quote=null, assetId=<redacted>)
...
// A bunch of similar missing referenced assets.
...
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
[main] WARN com.wire.backups.exports.android - Database is missing referenced message: Like(messageId=<redacted>, userId=<redacted>, timestamp=0)
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
<redacted>, id: <redacted>
Conversations map ready.
java.lang.NullPointerException
        at com.wire.backups.exports.exporters.AndroidExporter.lambda$getCollector$16(AndroidExporter.java:266)
        at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
        at com.wire.backups.exports.exporters.AndroidExporter.getCollector(AndroidExporter.java:263)
        at com.wire.backups.exports.exporters.AndroidExporter.lambda$appendMembers$7(AndroidExporter.java:160)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.wire.backups.exports.exporters.AndroidExporter.appendMembers(AndroidExporter.java:159)
        at com.wire.backups.exports.exporters.AndroidExporter.run(AndroidExporter.java:68)
        at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:27)
        at com.wire.backups.exports.commands.EncryptedClientCommand.call(EncryptedClientCommand.java:9)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.wire.backups.exports.Service.main(Service.java:15)
```
